"""Installation plan Tasks 3.3 and 3.5: ``scripts/build-release.py``.

Every mode runs against FAKE trees under ``tmp_path`` — fake models with fake
pins, a fake PyInstaller bundle, a fake build runner that records commands —
so nothing here builds, downloads, scans or reads the practitioner's models
(C6). The committed ``packaging/models-manifest.json`` is generated by the
practitioner (Task 3.3); while it is absent the test that reads it SKIPS by
name, and the same checks run on a fixture manifest."""

from __future__ import annotations

import ast
import hashlib
import importlib.util
import json
import subprocess
import sys
from pathlib import Path, PurePosixPath, PureWindowsPath
from types import ModuleType, SimpleNamespace
from typing import Any

import pytest

from scribe_desktop import identity, install_layout, language_model, speaker_embedding

REPO = Path(__file__).resolve().parents[2]
MANIFEST = REPO / "packaging" / "models-manifest.json"
ATTRIBUTION = REPO / "packaging" / "speaker-model-ATTRIBUTION.txt"

_MANIFEST_ABSENT = (
    "packaging/models-manifest.json is not generated yet - Task 3.3's practitioner step "
    "(scripts/build-release.py --write-manifest)"
)


def _load(stem: str) -> ModuleType:
    """A hyphenated script as a module. Registered in ``sys.modules`` first:
    ``dataclasses`` resolves a string annotation through the defining
    module's entry there."""
    path = REPO / "scripts" / f"{stem}.py"
    name = f"{stem.replace('-', '_')}_under_test"
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def release() -> ModuleType:
    return _load("build-release")


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


SILERO = b"silero model bytes"
SPEAKER = b"speaker model bytes" * 3
LANGUAGE = b"language model bytes" * 5


def _pins(release: ModuleType, tmp_path: Path) -> Any:
    attribution = tmp_path / "ATTRIBUTION.txt"
    attribution.write_bytes(b"CC BY 4.0 notice\n")
    return release.ModelPins(
        silero_path="silero-vad/silero_vad.onnx",
        silero_sha256=_sha(SILERO),
        speaker_path="speaker-embedding/speaker.onnx",
        speaker_size=len(SPEAKER),
        speaker_sha256=_sha(SPEAKER),
        language_path="language-model/lm.gguf",
        language_size=len(LANGUAGE),
        language_sha256=_sha(LANGUAGE),
        attribution_path="speaker-embedding/ATTRIBUTION.txt",
        attribution_source=attribution,
    )


def _models(root: Path) -> Path:
    files = {
        "silero-vad/silero_vad.onnx": SILERO,
        "speaker-embedding/speaker.onnx": SPEAKER,
        "language-model/lm.gguf": LANGUAGE,
        "whisper/medium/model.bin": b"weights",
        "whisper/medium/config.json": b"{}",
        "whisper/medium/tokenizer.json": b"{}",
        "whisper/medium/vocabulary.txt": b"a b",
        "whisper/medium/README.md": b"not a model file",
        "whisper/medium/.cache/huggingface/download/model.bin.metadata": b"hub bookkeeping",
        "whisper/small/model.bin": b"another candidate",
    }
    for relative, data in files.items():
        path = root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
    return root


class TestTheManifest:
    def test_it_lists_exactly_the_pack_and_checks_every_pin(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        pins = _pins(release, tmp_path)
        manifest = release.build_manifest(_models(tmp_path / "models"), pins)
        assert manifest["version"] == 1
        assert [f["path"] for f in manifest["files"]] == [
            "language-model/lm.gguf",
            "silero-vad/silero_vad.onnx",
            "speaker-embedding/ATTRIBUTION.txt",
            "speaker-embedding/speaker.onnx",
            "whisper/medium/config.json",
            "whisper/medium/model.bin",
            "whisper/medium/tokenizer.json",
            "whisper/medium/vocabulary.txt",
        ]
        by_path = {f["path"]: f for f in manifest["files"]}
        assert by_path["language-model/lm.gguf"] == {
            "path": "language-model/lm.gguf",
            "size": len(LANGUAGE),
            "sha256": _sha(LANGUAGE),
        }
        assert by_path["speaker-embedding/ATTRIBUTION.txt"]["sha256"] == _sha(
            b"CC BY 4.0 notice\n"
        )

    @pytest.mark.parametrize(
        ("damage", "message"),
        [
            ("silero-vad/silero_vad.onnx", "does not match its pinned SHA-256"),
            ("speaker-embedding/speaker.onnx", "not the pinned"),
            ("language-model/lm.gguf", "not the pinned"),
        ],
    )
    def test_a_file_off_its_pin_is_refused(
        self, release: ModuleType, tmp_path: Path, damage: str, message: str
    ) -> None:
        models = _models(tmp_path / "models")
        (models / damage).write_bytes(b"other")
        with pytest.raises(release.ReleaseError, match=message):
            release.build_manifest(models, _pins(release, tmp_path))

    def test_a_missing_pinned_file_is_refused(self, release: ModuleType, tmp_path: Path) -> None:
        models = _models(tmp_path / "models")
        (models / "language-model" / "lm.gguf").unlink()
        with pytest.raises(release.ReleaseError, match="lm.gguf is missing"):
            release.build_manifest(models, _pins(release, tmp_path))

    def test_an_incomplete_whisper_medium_is_refused(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        models = _models(tmp_path / "models")
        (models / "whisper" / "medium" / "model.bin").unlink()
        with pytest.raises(release.ReleaseError, match="whisper/medium is incomplete"):
            release.build_manifest(models, _pins(release, tmp_path))

    def test_the_digest_is_over_the_canonical_form(self, release: ModuleType) -> None:
        manifest = {"version": 1, "files": [{"path": "a/b", "size": 1, "sha256": "0" * 64}]}
        text = release.manifest_bytes(manifest)
        assert text.endswith(b"\n") and b"\r" not in text
        assert release.manifest_sha256(manifest) == _sha(text)

    @pytest.mark.parametrize(
        "path",
        ["../models/x.bin", "/abs/x.bin", "C:/x/y.bin", "a\\b.bin", "top.bin", "a/{app}.bin",
         "a/it's.bin", 'a/"q".bin', "a/./b.bin"],
    )
    def test_a_path_the_installer_cannot_carry_is_refused(
        self, release: ModuleType, path: str
    ) -> None:
        manifest = {"version": 1, "files": [{"path": path, "size": 1, "sha256": "0" * 64}]}
        with pytest.raises(release.ReleaseError):
            release.validate_manifest(manifest)

    @pytest.mark.parametrize(
        "entry",
        [
            {"path": "a/b", "size": -1, "sha256": "0" * 64},
            {"path": "a/b", "size": True, "sha256": "0" * 64},
            {"path": "a/b", "size": 1, "sha256": "A" * 64},
            {"path": "a/b", "size": 1, "sha256": "0" * 63},
            {"path": "a/b", "size": 1},
        ],
    )
    def test_a_malformed_entry_is_refused(self, release: ModuleType, entry: Any) -> None:
        with pytest.raises(release.ReleaseError):
            release.validate_manifest({"version": 1, "files": [entry]})

    def test_the_pack_name_is_install_layouts(self, release: ModuleType) -> None:
        manifest = {"version": 1, "files": [{"path": "a/b", "size": 1, "sha256": "0" * 64}]}
        digest = release.manifest_sha256(manifest)
        assert release.model_pack_name(manifest) == install_layout.model_pack_name(digest)
        assert release.model_pack_name(manifest) == "ClinikoScribe-models-" + digest[:8]

    def test_the_real_pins_are_the_runtimes(self, release: ModuleType) -> None:
        pins = release.model_pins()
        setup_models = _load("setup-models")
        assert pins.silero_sha256 == setup_models.SILERO_VAD_SHA256
        assert (pins.speaker_size, pins.speaker_sha256) == (
            speaker_embedding.SPEAKER_MODEL_SIZE_BYTES,
            speaker_embedding.SPEAKER_MODEL_SHA256,
        )
        assert (pins.language_size, pins.language_sha256) == (
            language_model.LANGUAGE_MODEL_SIZE_BYTES,
            language_model.LANGUAGE_MODEL_SHA256,
        )
        assert pins.speaker_path == "speaker-embedding/wespeaker-voxceleb-resnet34-LM.onnx"
        assert pins.language_path == "language-model/Qwen3-4B-Instruct-2507-Q4_K_M.gguf"
        assert pins.attribution_source == ATTRIBUTION

    @pytest.mark.skipif(not MANIFEST.is_file(), reason=_MANIFEST_ABSENT)
    def test_the_committed_manifest_matches_the_pins(self, release: ModuleType) -> None:
        manifest = release.load_manifest(MANIFEST)
        pins = release.model_pins()
        by_path = {f["path"]: f for f in manifest["files"]}
        assert by_path[pins.silero_path]["sha256"] == pins.silero_sha256
        assert (by_path[pins.speaker_path]["size"], by_path[pins.speaker_path]["sha256"]) == (
            pins.speaker_size,
            pins.speaker_sha256,
        )
        assert (by_path[pins.language_path]["size"], by_path[pins.language_path]["sha256"]) == (
            pins.language_size,
            pins.language_sha256,
        )
        assert by_path[pins.attribution_path]["sha256"] == release.sha256_file(ATTRIBUTION)
        whisper = {p for p in by_path if p.startswith("whisper/")}
        assert {"whisper/medium/model.bin", "whisper/medium/config.json"} <= whisper
        assert all(p.startswith("whisper/medium/") for p in whisper)
        tops = {PurePosixPath(p).parts[0] for p in by_path}
        assert tops == {"language-model", "silero-vad", "speaker-embedding", "whisper"}
        # Written by --write-manifest: its canonical form, byte for byte (LF).
        assert MANIFEST.read_bytes() == release.manifest_bytes(manifest)


class TestTheAttributionNotice:
    def test_it_carries_task_0_4s_terms(self) -> None:
        text = ATTRIBUTION.read_text(encoding="utf-8")
        assert "Creative Commons Attribution 4.0 International (CC BY 4.0)" in text
        assert "https://creativecommons.org/licenses/by/4.0/" in text
        assert "Wespeaker: A research and production oriented speaker" in text
        assert "unmodified (byte-identical, SHA-256-pinned)" in text
        assert _load("setup-models").SPEAKER_EMBEDDING_URL in text

    def test_its_bytes_are_the_same_on_every_checkout(self) -> None:
        attributes = (REPO / ".gitattributes").read_text(encoding="utf-8")
        assert "packaging/speaker-model-ATTRIBUTION.txt text eol=lf" in attributes
        assert "packaging/models-manifest.json text eol=lf" in attributes


def _manifest(release: ModuleType, tmp_path: Path) -> tuple[dict[str, Any], Path, Any]:
    pins = _pins(release, tmp_path)
    models = _models(tmp_path / "models")
    return release.build_manifest(models, pins), models, pins


class TestTheModelPack:
    def test_it_copies_exactly_the_manifest(self, release: ModuleType, tmp_path: Path) -> None:
        manifest, models, pins = _manifest(release, tmp_path)
        pack = release.make_model_pack(models, tmp_path / "out", manifest, pins)
        assert pack.name == release.model_pack_name(manifest)
        copied = sorted(p.relative_to(pack).as_posix() for p in pack.rglob("*") if p.is_file())
        assert copied == [f["path"] for f in manifest["files"]]
        assert (pack / "speaker-embedding" / "ATTRIBUTION.txt").read_bytes() == (
            b"CC BY 4.0 notice\n"
        )

    @pytest.mark.parametrize(
        ("relative", "data", "message"),
        [
            ("whisper/medium/model.bin", None, "is missing"),
            ("whisper/medium/model.bin", b"weightz", "does not match"),
            ("whisper/medium/model.bin", b"weights!", "is not 7 bytes"),
        ],
    )
    def test_a_bad_source_refuses_and_writes_nothing(
        self,
        release: ModuleType,
        tmp_path: Path,
        relative: str,
        data: bytes | None,
        message: str,
    ) -> None:
        manifest, models, pins = _manifest(release, tmp_path)
        if data is None:
            (models / relative).unlink()
        else:
            (models / relative).write_bytes(data)
        out = tmp_path / "out"
        with pytest.raises(release.ReleaseError, match=message):
            release.make_model_pack(models, out, manifest, pins)
        assert not out.exists()

    def test_an_existing_pack_is_never_overwritten(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        manifest, models, pins = _manifest(release, tmp_path)
        out = tmp_path / "out"
        (out / release.model_pack_name(manifest)).mkdir(parents=True)
        with pytest.raises(release.ReleaseError, match="already exists"):
            release.make_model_pack(models, out, manifest, pins)


def _names(word: str) -> set[str]:
    """What a key may match in one command word: the word itself, and the name
    and stem of its last path part (``ISCC`` for ``…\\ISCC.exe``) — NEVER a
    substring of a path, so a temporary folder named after the test (pytest's
    ``…_status0``) can never answer for another command (round 20 fix-delta)."""
    name = PureWindowsPath(word).name
    return {word, name, PureWindowsPath(name).stem}


class _Runner:
    """Records every command; answers with the code ``codes`` maps a key to
    (default 0), ``outputs`` its stdout and ``errors`` its stderr — a key
    matching one WORD of the command (``_names``), never part of a path."""

    def __init__(
        self,
        codes: dict[str, int] | None = None,
        outputs: dict[str, str] | None = None,
        errors: dict[str, str] | None = None,
    ) -> None:
        self.commands: list[list[str]] = []
        self.envs: list[dict[str, str] | None] = []
        self.codes = codes or {}
        self.outputs = outputs or {}
        self.errors = errors or {}

    def __call__(self, command: Any, **kwargs: Any) -> Any:
        words = [str(part) for part in command]
        self.commands.append(words)
        self.envs.append(kwargs.get("env"))
        names = set().union(*(_names(word) for word in words))
        code = next((v for k, v in self.codes.items() if k in names), 0)
        out = next((v for k, v in self.outputs.items() if k in names), "")
        err = next((v for k, v in self.errors.items() if k in names), "")
        return SimpleNamespace(returncode=code, stdout=out, stderr=err)


def test_the_pack_ships_the_apps_own_whisper_model() -> None:
    """H.3 SIMP-001: the whisper model is named once (``benchmark``); the
    app's default and the model pack read it, so they cannot drift apart."""
    from scribe_desktop import benchmark, transcription

    assert transcription.DEFAULT_WHISPER_MODEL is benchmark.SHIPPED_WHISPER_MODEL
    source = (REPO / "scripts" / "build-release.py").read_text(encoding="utf-8")
    assert '"medium"' not in source and "WHISPER_PACK_MODEL" not in source
    assert "SHIPPED_WHISPER_MODEL" in source


def test_the_fake_runner_matches_words_never_paths() -> None:
    """Round 20 fix-delta: pytest names a test's temporary folder after the
    test (``…_status0``), so a key found ANYWHERE in the joined command line
    made ``rev-parse`` answer as ``status``. A key now matches one word (or a
    program's file name and stem), never part of a path."""
    run = _Runner(codes={"status": 128, "ISCC": 2})
    source = r"C:\Temp\pytest-of-x\test_preflight_refusals_status0\pyinstaller-src"
    assert run(["git", "-C", source, "rev-parse", "HEAD"]).returncode == 0
    assert run(["git", "-C", source, "status", "--porcelain"]).returncode == 128
    assert run([r"C:\Program Files (x86)\Inno Setup 6\ISCC.exe", "/O" + source]).returncode == 2
    assert run(["git", "-C", r"C:\ISCC-builds\x", "rev-parse"]).returncode == 0


def _bundle(release: ModuleType, root: Path) -> Path:
    bundle = root / "dist" / "scribe"
    for exe in ("scribe-app.exe", "scribe-host.exe"):
        (bundle / exe).parent.mkdir(parents=True, exist_ok=True)
        (bundle / exe).write_bytes(b"MZ")
    defaults = REPO / "desktop" / "src" / "scribe_desktop" / "config_defaults"
    target = bundle / "_internal" / "scribe_desktop" / "config_defaults"
    target.mkdir(parents=True)
    for file in defaults.glob("*.json"):
        (target / file.name).write_bytes(b"{}")
    for folder in release.NATIVE_LIBRARY_DIRS:
        (bundle / "_internal" / folder).mkdir(parents=True, exist_ok=True)
        (bundle / "_internal" / folder / "lib.dll").write_bytes(b"MZ")
    (bundle / "_internal" / "PySide6").mkdir()
    (bundle / "_internal" / "PySide6" / "Qt6Core.dll").write_bytes(b"MZ")
    return bundle


class TestTheAudit:
    def test_a_good_bundle_passes_and_the_self_check_runs_hostile(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        bundle = _bundle(release, tmp_path)
        run = _Runner()
        assert release.audit_bundle(bundle, run) == []
        [command] = run.commands
        assert command == [str(bundle / "scribe-app.exe"), "--self-check-offline"]
        [env] = run.envs
        assert env is not None
        for name, value in release.HOSTILE_ENV.items():
            assert env[name] == value
        assert set(release.HOSTILE_ENV) >= {"SSLKEYLOGFILE", "LLAMA_CPP_LIB_PATH", "HF_HUB_OFFLINE"}

    def test_every_variable_the_app_enforces_is_set_wrong(self, release: ModuleType) -> None:
        """Round 18 LOW-002: the audit's hostile set is EXACTLY what the app
        sets or refuses (a new kill-switch must be exercised too), and each
        value is wrong: a kill-switch not at its required value, an override
        present."""
        from scribe_desktop import benchmark

        overrides = {*benchmark.FORBIDDEN_NATIVE_OVERRIDES, *benchmark.FORBIDDEN_TLS_OVERRIDES}
        assert set(release.HOSTILE_ENV) == set(benchmark.OFFLINE_ENV) | overrides
        for name, required in benchmark.OFFLINE_ENV.items():
            assert release.HOSTILE_ENV[name] != required, name
        for name in overrides:
            assert release.HOSTILE_ENV[name], name

    def test_the_flag_is_the_apps(self, release: ModuleType) -> None:
        from scribe_desktop import app

        assert release.SELF_CHECK_FLAG == app.SELF_CHECK_FLAG

    @pytest.mark.parametrize(
        ("damage", "message"),
        [
            ("scribe-host.exe", "scribe-host.exe is missing"),
            ("_internal/scribe_desktop/config_defaults/section_cues.json", "section_cues.json"),
            ("_internal/llama_cpp/lib/lib.dll", "no native library in _internal/llama_cpp/lib"),
        ],
    )
    def test_a_missing_part_fails(
        self, release: ModuleType, tmp_path: Path, damage: str, message: str
    ) -> None:
        bundle = _bundle(release, tmp_path)
        (bundle / damage).unlink()
        failures = release.audit_bundle(bundle, _Runner())
        assert any(message in f for f in failures), failures

    @pytest.mark.parametrize(
        "name",
        ["PySide6/Qt6Network.dll", "PySide6/QtNetwork.pyd", "PySide6/plugins/tls/qopenssl.dll"],
    )
    def test_any_qt_networking_file_fails(
        self, release: ModuleType, tmp_path: Path, name: str
    ) -> None:
        bundle = _bundle(release, tmp_path)
        path = bundle / "_internal" / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(b"MZ")
        assert release.audit_bundle(bundle, _Runner()) == [
            f"Qt networking is bundled: _internal/{name}"
        ]

    @pytest.mark.parametrize("code", [1, 2])
    def test_a_failed_self_check_fails(
        self, release: ModuleType, tmp_path: Path, code: int
    ) -> None:
        bundle = _bundle(release, tmp_path)
        failures = release.audit_bundle(bundle, _Runner({"--self-check-offline": code}))
        assert failures == [
            f"the offline self-check exited {code} "
            "(1: the offline variables; 2: a Qt networking module is importable)"
        ]

    def test_a_self_check_that_never_ends_fails(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        """Round 23: the self-check is bounded (a start-up error box nobody
        clicks would otherwise hang the build), and a timeout is a failure."""
        bundle = _bundle(release, tmp_path)
        run = _Runner({"--self-check-offline": release.TIMED_OUT})
        timeouts: list[object] = []

        def recording(command: Any, **kwargs: Any) -> Any:
            timeouts.append(kwargs.get("timeout"))
            return run(command, **kwargs)

        assert release.audit_bundle(bundle, recording) == [
            f"the offline self-check did not finish within {release.SELF_CHECK_TIMEOUT_S} s "
            "(a start-up error box waiting for a click?)"
        ]
        assert timeouts == [release.SELF_CHECK_TIMEOUT_S]

    def test_the_runner_reports_a_timeout_and_refuses_a_missing_tool(
        self, release: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Round 23: ``_run`` turns a timeout into ``TIMED_OUT`` and a program
        that cannot be started into a named refusal, never a traceback."""

        def expire(*args: Any, **kwargs: Any) -> Any:
            raise subprocess.TimeoutExpired(cmd="x", timeout=kwargs["timeout"])

        with monkeypatch.context() as patch:
            patch.setattr(release.subprocess, "run", expire)
            assert release._run(["x"], timeout=1).returncode == release.TIMED_OUT
        missing = tmp_path / "ISCC.exe"
        with pytest.raises(release.ReleaseError, match="could not start .*ISCC.exe"):
            release._run([missing, "/?"])

    @pytest.mark.parametrize(
        ("code", "verdict"), [(0, "clean"), (3, "detected"), (1, "not run (exit 1)")]
    )
    def test_the_defender_scan_never_reports_unrun_as_clean(
        self, release: ModuleType, tmp_path: Path, code: int, verdict: str
    ) -> None:
        run = _Runner({"powershell.exe": code})
        assert release.defender_scan(tmp_path, run) == verdict
        [command] = run.commands
        assert "Start-MpScan -ScanType CustomScan" in command[-1]

    @pytest.mark.parametrize("quote", ["'", "‘", "’", "‚", "‛"])
    def test_a_quote_in_the_path_never_reaches_powershell(
        self, release: ModuleType, tmp_path: Path, quote: str
    ) -> None:
        """H.4 SEC-004: every character PowerShell reads as a single quote is
        refused before the scan's command line is built."""
        run = _Runner()
        assert release.defender_scan(tmp_path / f"a{quote}b", run) == (
            "not run (the path holds a quote)"
        )
        assert run.commands == []

    @pytest.mark.parametrize(("code", "exit_code"), [(3, 1), (0, 0), (1, 0)])
    def test_a_defender_detection_fails_the_audit_cli(
        self,
        release: ModuleType,
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
        code: int,
        exit_code: int,
    ) -> None:
        """Round 20 PR-HIGH-002: ``--audit`` exits 1 on a detection, as the
        build refuses one; clean and not-run (shown as such) keep a passing
        audit's 0."""
        bundle = _bundle(release, tmp_path)
        run = _Runner({"powershell.exe": code})
        assert release.main(["--audit", str(bundle)], run=run) == exit_code
        out = capsys.readouterr().out
        if exit_code:
            assert "defender : detected" in out
            assert f"FAIL     : {release.DEFENDER_DETECTED}" in out
        else:
            assert "FAIL" not in out and "audit: OK" in out

    def test_the_audit_cli_exits_1_on_a_failure(
        self, release: ModuleType, tmp_path: Path, capsys: pytest.CaptureFixture[str]
    ) -> None:
        bundle = _bundle(release, tmp_path)
        (bundle / "scribe-app.exe").unlink()
        assert release.main(["--audit", str(bundle), "--no-defender"], run=_Runner()) == 1
        out = capsys.readouterr().out
        assert "FAIL     : scribe-app.exe is missing" in out and "audit: FAIL" in out


class TestTheExtensionAudit:
    def _extension(self, root: Path, name: str, host: str) -> Path:
        root.mkdir(parents=True)
        (root / "manifest.json").write_text(json.dumps({"name": name}), encoding="utf-8")
        (root / "background.js").write_text(f'const h="{host}";', encoding="utf-8")
        return root

    def test_the_release_build_passes(self, release: ModuleType, tmp_path: Path) -> None:
        ext = self._extension(tmp_path / "ext", "Clinic Scribe Companion", identity.HOST_NAME)
        assert release.audit_extension(ext) == []

    def test_the_dev_build_fails(self, release: ModuleType, tmp_path: Path) -> None:
        ext = self._extension(
            tmp_path / "ext", "Clinic Scribe Companion (dev)", identity.DEV_HOST_NAME
        )
        failures = release.audit_extension(ext)
        assert "the extension is the dev build" in failures
        assert "the extension names the dev host" in failures


class TestTheInstallerInputs:
    def test_the_host_manifest_is_the_production_link_at_the_install_folder(
        self, release: ModuleType
    ) -> None:
        manifest = release.host_manifest()
        assert manifest["name"] == identity.HOST_NAME
        assert manifest["allowed_origins"] == [identity.EXPECTED_ORIGIN]
        assert manifest["path"] == install_layout.INSTALL_ROOTS[0] + r"\scribe-host.exe"
        assert manifest["type"] == "stdio"
        assert release.host_manifest_name() == f"{identity.HOST_NAME}.json"

    def test_the_includes_carry_every_file_and_hash(self, release: ModuleType) -> None:
        manifest = {
            "version": 1,
            "files": [
                {"path": "language-model/lm.gguf", "size": 3, "sha256": "a" * 64},
                {"path": "whisper/medium/model.bin", "size": 4, "sha256": "b" * 64},
            ],
        }
        files, code = release.inno_includes(manifest, "ClinikoScribe-models-12345678")
        assert (
            'Source: "{src}\\ClinikoScribe-models-12345678\\whisper\\medium\\model.bin"; '
            'DestDir: "{app}\\models\\whisper\\medium"; '
            "Flags: external ignoreversion; Check: ModelsNeedCopy"
        ) in files
        assert "  AddModelFile('language-model\\lm.gguf', '" + "a" * 64 + "');" in code
        assert code.count("AddModelFile(") == 2
        assert "procedure AddModelFiles();" in code
        assert "{ " not in code  # the .iss's [Code] uses // comments only

    def test_the_sums_cover_every_output(self, release: ModuleType, tmp_path: Path) -> None:
        (tmp_path / "ClinikoScribe-0.1.0-setup.exe").write_bytes(b"setup")
        (tmp_path / "models-manifest.json").write_bytes(b"{}")
        sums = release.write_sums(tmp_path)
        assert sums.read_text(encoding="utf-8").splitlines() == [
            f"{_sha(b'setup')}  ClinikoScribe-0.1.0-setup.exe",
            f"{_sha(b'{}')}  models-manifest.json",
        ]
        release.write_sums(tmp_path)  # never lists itself
        assert "SHA256SUMS.txt" not in sums.read_text(encoding="utf-8")

    def test_the_version_is_pyprojects(self, release: ModuleType) -> None:
        from scribe_desktop import __version__

        assert release.app_version() == __version__


@pytest.fixture
def build_inputs(
    release: ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> dict[str, Path]:
    """A committed lock and manifest stand-in, and a PyInstaller source whose
    bootloader the fake ``waf`` rebuilds and whose pyproject declares the
    pinned build backend (which the lock stand-in carries, round 31)."""
    lock = tmp_path / "requirements-build.txt"
    lock.write_text(
        "# lock\n" + f"hatchling==1.32.4 \\\n    --hash=sha256:{'0' * 64}\n", encoding="utf-8"
    )
    manifest_path = tmp_path / "models-manifest.json"
    manifest = {"version": 1, "files": [{"path": "a/b.bin", "size": 1, "sha256": "0" * 64}]}
    manifest_path.write_bytes(release.manifest_bytes(manifest))
    monkeypatch.setattr(release, "LOCK", lock)
    monkeypatch.setattr(release, "MANIFEST_PATH", manifest_path)
    source = tmp_path / "pyinstaller-src"
    (source / release.RUNW).parent.mkdir(parents=True)
    (source / release.RUNW).write_bytes(b"rebuilt bootloader")
    (source / "pyproject.toml").write_text(_PYINSTALLER_PYPROJECT, encoding="utf-8")
    return {"source": source, "out": tmp_path / "release", "manifest": manifest_path}


# PyInstaller v6.22.3's own [build-system] (round 31; the first Release run).
_PYINSTALLER_PYPROJECT = (
    '[build-system]\nrequires = ["hatchling"]\nbuild-backend = "hatchling.build"\n'
)


class TestNoRepoArtefactIsRead:
    """C6: a test never depends on whether the practitioner's artefacts (the
    lock, the models manifest) exist yet. Every reader resolves its repo path
    at CALL time, so the ``build_inputs`` stand-ins are what it reads."""

    def test_the_manifest_reader_follows_the_stand_in(
        self, release: ModuleType, build_inputs: dict[str, Path]
    ) -> None:
        assert release.load_manifest() == json.loads(build_inputs["manifest"].read_text())
        build_inputs["manifest"].unlink()
        with pytest.raises(release.ReleaseError, match="--write-manifest"):
            release.load_manifest()

    @pytest.mark.parametrize("stem", ["build-release", "lock-build-requirements"])
    def test_no_function_binds_a_module_constant_as_a_default(self, stem: str) -> None:
        tree = ast.parse((REPO / "scripts" / f"{stem}.py").read_text(encoding="utf-8"))
        bound = [
            f"{node.name}={default.id}"
            for node in ast.walk(tree)
            if isinstance(node, ast.FunctionDef)
            for default in [*node.args.defaults, *node.args.kw_defaults]
            if isinstance(default, ast.Name) and default.id.isupper()
        ]
        assert bound == []


def _commit(release: ModuleType) -> dict[str, str]:
    return {"rev-parse": release.PYINSTALLER_COMMIT + "\n"}


class TestStageOne:
    def test_the_clean_environment_then_pyinstaller_from_source(
        self, release: ModuleType, build_inputs: dict[str, Path], monkeypatch: pytest.MonkeyPatch
    ) -> None:
        run = _Runner(outputs=_commit(release))
        out, source = build_inputs["out"], build_inputs["source"]
        release.preflight(source, out, run=run, version_info=(3, 14, 6), platform="win32")
        run.commands.clear()
        monkeypatch.setattr(
            release, "preflight", lambda *a, **k: None
        )  # proven above; stage_one's own call
        release.stage_one(source, out, Path("ISCC.exe"), defender=True, run=run)
        python = str(out / "build-venv" / "Scripts" / "python.exe")
        steps = [" ".join(c) for c in run.commands]
        assert steps[0].endswith(f"-m venv {out / 'build-venv'}")
        assert steps[1] == f"{python} -m pip install --require-hashes --no-deps -r {release.LOCK}"
        assert steps[2] == (
            f"{python} -m pip install --require-hashes --no-deps -r {release.PROSE_LOCK}"
        )
        assert steps[3] == f"{python} ./waf all --target-arch=64bit"
        assert steps[4] == (
            f"{python} -m pip install --no-deps --no-build-isolation {source}"
        )
        assert steps[5] == f"{python} -m pip check"
        assert steps[6].startswith(f"{python} ") and "--continue-build" in steps[6]
        assert "--no-defender" not in steps[6]

    def test_an_unrebuilt_bootloader_is_refused(
        self, release: ModuleType, build_inputs: dict[str, Path], monkeypatch: pytest.MonkeyPatch
    ) -> None:
        source = build_inputs["source"]
        monkeypatch.setattr(release, "preflight", lambda *a, **k: None)
        monkeypatch.setattr(release, "sha256_file", lambda path: release.SHIPPED_RUNW_SHA256)
        with pytest.raises(release.ReleaseError, match="was not rebuilt"):
            release.stage_one(
                source, build_inputs["out"], Path("ISCC.exe"), defender=True, run=_Runner()
            )

    @pytest.mark.parametrize(
        ("change", "message"),
        [
            ("python", "Python 3.14"),
            ("platform", "on Windows"),
            ("lock", "requirements-build.txt does not exist"),
            ("manifest", "--write-manifest"),
            ("out", "is not empty"),
            ("commit", "is not PyInstaller 6.22.3"),
            ("dirty", "has local changes or extra files"),
            ("ignored", "clone it again into an empty folder"),
            ("status fails", "has local changes or extra files"),
            ("lock lacks the backend", "lacks hatchling, the build backend"),
            ("backend changed", "declares the build requirements hatchling, hatch-vcs"),
            ("no pyproject", "does not declare its build requirements"),
            ("no build-system", "does not declare its build requirements"),
        ],
    )
    def test_preflight_refusals(
        self,
        release: ModuleType,
        build_inputs: dict[str, Path],
        change: str,
        message: str,
    ) -> None:
        version, platform, outputs = (3, 14, 6), "win32", _commit(release)
        codes: dict[str, int] = {}
        if change == "dirty":
            outputs |= {"status": " M PyInstaller/bootloader/src/pyi_main.c\n"}
        elif change == "ignored":
            outputs |= {"status": "!! bootloader/build/\n"}
        elif change == "status fails":
            codes = {"status": 128}
        if change == "python":
            version = (3, 12, 9)
        elif change == "platform":
            platform = "linux"
        elif change == "lock":
            release.LOCK.unlink()
        elif change == "manifest":
            build_inputs["manifest"].unlink()
        elif change == "out":
            build_inputs["out"].mkdir()
            (build_inputs["out"] / "stale").write_bytes(b"x")
        elif change == "commit":
            outputs = {"rev-parse": "0" * 40 + "\n"}
        elif change == "lock lacks the backend":
            release.LOCK.write_text(
                f"altgraph==0.17.5 \\\n    --hash=sha256:{'0' * 64}\n", encoding="utf-8"
            )
        elif change == "backend changed":
            (build_inputs["source"] / "pyproject.toml").write_text(
                '[build-system]\nrequires = ["hatchling>=1.20", "hatch_vcs"]\n', encoding="utf-8"
            )
        elif change == "no pyproject":
            (build_inputs["source"] / "pyproject.toml").unlink()
        elif change == "no build-system":
            (build_inputs["source"] / "pyproject.toml").write_text(
                '[project]\nname = "pyinstaller"\n', encoding="utf-8"
            )
        with pytest.raises(release.ReleaseError, match=message):
            release.preflight(
                build_inputs["source"],
                build_inputs["out"],
                run=_Runner(codes=codes, outputs=outputs),
                version_info=version,
                platform=platform,
            )

    def test_the_source_tree_is_checked_whole_before_waf(
        self, release: ModuleType, build_inputs: dict[str, Path], monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Round 20 PR-HIGH-001: the PyInstaller source is checked for changed,
        untracked AND ignored files, before the bootloader build rewrites it."""
        run = _Runner(outputs=_commit(release))
        original = release.preflight

        def pinned_preflight(source: Path, out: Path, *, run: Any) -> None:
            # The interpreter and platform are injected, never this host's (C6).
            original(source, out, run=run, version_info=(3, 14, 6), platform="win32")

        monkeypatch.setattr(release, "preflight", pinned_preflight)
        release.stage_one(
            build_inputs["source"], build_inputs["out"], Path("ISCC.exe"), defender=True, run=run
        )
        steps = [" ".join(c) for c in run.commands]
        [status] = [i for i, s in enumerate(steps) if " status " in s]
        assert steps[status].endswith("status --porcelain --untracked-files=all --ignored")
        assert str(build_inputs["source"]) in steps[status]
        waf = next(i for i, s in enumerate(steps) if "./waf" in s)
        assert status < waf

    def test_the_pins_are_task_0_1s(self, release: ModuleType) -> None:
        assert release.BUILD_PYTHON == (3, 14)
        assert release.PYINSTALLER_VERSION == "6.22.3"
        assert release.PYINSTALLER_COMMIT == "ecd7993d65c43b254f4e3f718e36d5b4a70a3ed5"
        assert release.SHIPPED_RUNW_SHA256 == (
            "2291F269C3A3804FDE1079462239E09A8B32FFFBEEAA8F628A531FAF5BE77D41".lower()
        )
        assert release.INNO_BANNER == "Compiler engine version: Inno Setup 6.7.3"

    def test_every_build_requirement_of_pyinstaller_is_locked(self, release: ModuleType) -> None:
        """Round 31 (the first Release run failed on it): PyInstaller's source
        is installed WITHOUT build isolation, so every build requirement of the
        pinned commit — and the backend's own dependencies — must be pinned in
        the lock generator, or the build venv cannot build it. A PyInstaller
        bump changes PYINSTALLER_BUILD_REQUIRES's source and forces this
        re-check."""
        assert release.PYINSTALLER_BUILD_REQUIRES == ("hatchling",)
        lock = _load("lock-build-requirements")
        for name in release.PYINSTALLER_BUILD_REQUIRES:
            assert name in lock.BUILD_TOOL_PINS, name
            assert name in lock.EXTRA_REQUIREMENTS, name
        # hatchling 1.32.4's Requires-Dist (packaging comes from the freeze).
        assert {"pathspec", "pluggy", "tomlkit", "trove-classifiers"} <= set(lock.BUILD_TOOL_PINS)
        assert "packaging" in lock.EXTRA_REQUIREMENTS

    def test_the_backend_is_read_from_the_source(
        self, release: ModuleType, tmp_path: Path
    ) -> None:
        (tmp_path / "pyproject.toml").write_text(_PYINSTALLER_PYPROJECT, encoding="utf-8")
        assert release.pyinstaller_build_requires(tmp_path) == ["hatchling"]
        (tmp_path / "pyproject.toml").write_text(
            '[build-system]\nrequires = ["Hatch_VCS >= 0.3", "hatchling"]\n', encoding="utf-8"
        )
        assert release.pyinstaller_build_requires(tmp_path) == ["hatch-vcs", "hatchling"]


class TestTheBuildRecord:
    """Round 20 (PR-HIGH-001's sibling): every build records this checkout's
    commit and whether its tree was clean — recorded, not refused (D7's local
    builds serve spikes)."""

    @pytest.mark.parametrize(
        ("codes", "outputs", "state"),
        [
            ({}, {"rev-parse": "a" * 40 + "\n"}, ("a" * 40, "clean")),
            (
                {},
                {"rev-parse": "a" * 40 + "\n", "status": " M scripts/x.py\n"},
                ("a" * 40, "DIRTY"),
            ),
            ({"rev-parse": 128, "status": 128}, {}, ("unknown", "unknown")),
            ({}, {"rev-parse": "not a commit\n"}, ("unknown", "clean")),
        ],
    )
    def test_the_source_state(
        self,
        release: ModuleType,
        codes: dict[str, int],
        outputs: dict[str, str],
        state: tuple[str, str],
    ) -> None:
        run = _Runner(codes=codes, outputs=outputs)
        assert release.source_state(run) == state
        assert all(command[:3] == ["git", "-C", str(release.REPO)] for command in run.commands)

    def test_the_build_writes_it_beside_the_setup_and_sums_it(
        self,
        release: ModuleType,
        build_inputs: dict[str, Path],
        monkeypatch: pytest.MonkeyPatch,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        out = build_inputs["out"]
        (out / "dist" / release.COLLECT_NAME).mkdir(parents=True)

        def fake_compile(bundle: Path, work: Path, out: Path, iscc: Path, run: Any) -> Path:
            setup = out / "installer" / "ClinikoScribe-0.1.0-setup.exe"
            setup.parent.mkdir(parents=True)
            setup.write_bytes(b"setup")
            return setup

        monkeypatch.setattr(release, "audit_bundle", lambda bundle, run: [])
        monkeypatch.setattr(release, "build_extension", lambda target, run: None)
        monkeypatch.setattr(release, "audit_extension", lambda folder: [])
        monkeypatch.setattr(release, "compile_installer", fake_compile)
        run = _Runner(outputs={"rev-parse": "b" * 40 + "\n", "status": "?? stray.txt\n"})
        assert release.stage_two(out, Path("ISCC.exe"), defender=False, run=run) == 0
        installer = out / "installer"
        info = (installer / "BUILD-INFO.txt").read_text(encoding="utf-8")
        assert info == f"version={release.app_version()}\ncommit={'b' * 40}\ntree=DIRTY\n"
        sums = (installer / "SHA256SUMS.txt").read_text(encoding="utf-8")
        assert "  BUILD-INFO.txt" in sums
        printed = capsys.readouterr().out
        assert f"source   : {'b' * 40} (DIRTY)" in printed
        assert "never the build of record (D7)" in printed

    def test_the_bundle_is_audited_after_the_extension_build(
        self,
        release: ModuleType,
        build_inputs: dict[str, Path],
        monkeypatch: pytest.MonkeyPatch,
    ) -> None:
        """H.4 SEC-001: the npm build can write into the bundle, so the bundle
        audit runs after it and only then is the installer compiled."""
        out = build_inputs["out"]
        (out / "dist" / release.COLLECT_NAME).mkdir(parents=True)
        order: list[str] = []

        def fake_compile(bundle: Path, work: Path, out: Path, iscc: Path, run: Any) -> Path:
            order.append("compile")
            setup = out / "installer" / "ClinikoScribe-0.1.0-setup.exe"
            setup.parent.mkdir(parents=True)
            setup.write_bytes(b"setup")
            return setup

        monkeypatch.setattr(
            release, "build_extension", lambda target, run: order.append("extension")
        )
        monkeypatch.setattr(
            release, "audit_bundle", lambda bundle, run: order.append("audit") or []
        )
        monkeypatch.setattr(release, "audit_extension", lambda folder: [])
        monkeypatch.setattr(release, "compile_installer", fake_compile)
        run = _Runner(outputs={"rev-parse": "b" * 40 + "\n"})
        assert release.stage_two(out, Path("ISCC.exe"), defender=False, run=run) == 0
        assert order == ["extension", "audit", "compile"]


class TestTheInstallerCompile:
    def test_iscc_gets_every_define_and_the_banner_is_checked(
        self, release: ModuleType, build_inputs: dict[str, Path], tmp_path: Path
    ) -> None:
        out = build_inputs["out"]
        out.mkdir()

        class Iscc(_Runner):
            def __call__(self, command: Any, **kwargs: Any) -> Any:
                result = super().__call__(command, **kwargs)
                target = Path(next(w for w in self.commands[-1] if w.startswith("/O"))[2:])
                (target / "ClinikoScribe-0.1.0-setup.exe").write_bytes(b"setup")
                return result

        run = Iscc(outputs={"ISCC": "Compiler engine version: Inno Setup 6.7.3\n"})
        setup = release.compile_installer(
            tmp_path / "bundle", tmp_path / "work", out, Path("ISCC.exe"), run
        )
        [command] = run.commands
        manifest = release.load_manifest()
        assert f"/DAppVersion={release.app_version()}" in command
        assert f"/DModelPackDir={release.model_pack_name(manifest)}" in command
        assert f"/DDistDir={tmp_path / 'bundle'}" in command
        assert command[-1] == str(release.ISS)
        assert setup.name == "ClinikoScribe-0.1.0-setup.exe"
        assert (out / "installer" / "models-manifest.json").is_file()

    def test_another_inno_version_is_refused_and_its_output_removed(
        self, release: ModuleType, build_inputs: dict[str, Path], tmp_path: Path
    ) -> None:
        out = build_inputs["out"]
        out.mkdir()

        class Iscc(_Runner):
            def __call__(self, command: Any, **kwargs: Any) -> Any:
                result = super().__call__(command, **kwargs)
                target = Path(next(w for w in self.commands[-1] if w.startswith("/O"))[2:])
                (target / "setup.exe").write_bytes(b"setup")
                return result

        run = Iscc(outputs={"ISCC": "Compiler engine version: Inno Setup 6.7.1\n"})
        with pytest.raises(release.ReleaseError, match="not compiled by Inno Setup 6.7.3"):
            release.compile_installer(
                tmp_path / "bundle", tmp_path / "work", out, Path("ISCC.exe"), run
            )
        assert list((out / "installer").iterdir()) == []

    def test_a_refused_compile_shows_the_compilers_own_words(
        self,
        release: ModuleType,
        build_inputs: dict[str, Path],
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        """Round 19 LOW-001: the output is captured for the banner check, so a
        failed compile shows it — never only an exit code."""
        out = build_inputs["out"]
        out.mkdir()
        run = _Runner(
            codes={"ISCC": 2},
            outputs={"ISCC": "Compiler engine version: Inno Setup 6.7.3\n"},
            errors={"ISCC": "Error on line 74 in scribe.iss: Unknown identifier\n"},
        )
        with pytest.raises(release.ReleaseError, match="Inno Setup failed"):
            release.compile_installer(
                tmp_path / "bundle", tmp_path / "work", out, Path("ISCC.exe"), run
            )
        assert "Error on line 74 in scribe.iss: Unknown identifier" in capsys.readouterr().err

    def test_a_good_compile_prints_nothing_extra(
        self,
        release: ModuleType,
        build_inputs: dict[str, Path],
        tmp_path: Path,
        capsys: pytest.CaptureFixture[str],
    ) -> None:
        out = build_inputs["out"]
        out.mkdir()

        class Iscc(_Runner):
            def __call__(self, command: Any, **kwargs: Any) -> Any:
                result = super().__call__(command, **kwargs)
                target = Path(next(w for w in self.commands[-1] if w.startswith("/O"))[2:])
                (target / "setup.exe").write_bytes(b"setup")
                return result

        run = Iscc(outputs={"ISCC": "Compiler engine version: Inno Setup 6.7.3\n"})
        release.compile_installer(
            tmp_path / "bundle", tmp_path / "work", out, Path("ISCC.exe"), run
        )
        assert capsys.readouterr().err == ""
