"""Installation plan Task 3.1: the hashed build lock.

``scripts/lock-build-requirements.py`` is driven against FAKE inputs — a
fixture freeze, and a fake ``pip download`` that writes made-up wheel files —
so nothing here touches the network or a real environment. The committed lock
``desktop/requirements-build.txt`` is generated by the practitioner (a
build-time network step); while it is absent, the tests that read it SKIP by
name, and the same checks run against a fixture lock so they never pass
vacuously."""

from __future__ import annotations

import hashlib
import importlib.util
import tomllib
from collections.abc import Callable, Sequence
from pathlib import Path
from types import ModuleType

import pytest

REPO = Path(__file__).resolve().parents[2]
LOCK = REPO / "desktop" / "requirements-build.txt"
PYPROJECT_TEXT = (REPO / "desktop" / "pyproject.toml").read_text(encoding="utf-8")

_LOCK_ABSENT = (
    "desktop/requirements-build.txt is not generated yet - Task 3.1's practitioner step "
    "(scripts/lock-build-requirements.py, a build-time network step)"
)


def _load() -> ModuleType:
    path = REPO / "scripts" / "lock-build-requirements.py"
    spec = importlib.util.spec_from_file_location("lock_build_requirements", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.fixture(scope="module")
def lock_script() -> ModuleType:
    return _load()


def _runtime_names(script: ModuleType) -> list[str]:
    names = [script.requirement_name(r) for r in script.runtime_requirements(PYPROJECT_TEXT)]
    return names + [script.requirement_name(r) for r in script.EXTRA_REQUIREMENTS]


def _freeze(script: ModuleType) -> str:
    """A freeze pinning every requirement, plus the lines a real one has
    that must be skipped."""
    lines = [f"{name}==1.0.{i}" for i, name in enumerate(_runtime_names(script))]
    lines += [
        "-e git+https://example.invalid/repo@abc#egg=scribe_desktop",
        "llama_cpp_python @ https://example.invalid/llama.whl",
        "pytest==9.0.0",
    ]
    return "\n".join(lines) + "\n"


def _fake_download(
    script: ModuleType, versions: dict[str, str], extra_files: Sequence[str] = ()
) -> tuple[list[list[str]], Callable[[Sequence[str]], int]]:
    commands: list[list[str]] = []

    def run(command: Sequence[str]) -> int:
        commands.append(list(command))
        dest = Path(command[command.index("--dest") + 1])
        for name, version in versions.items():
            stem = name.replace("-", "_")
            (dest / f"{stem}-{version}-py3-none-win_amd64.whl").write_bytes(
                f"{name} {version}".encode()
            )
        for filename in extra_files:
            (dest / filename).write_bytes(b"x")
        return 0

    return commands, run


def _all_versions(script: ModuleType) -> dict[str, str]:
    pins = script.proven_pins(_freeze(script)) | dict(script.BUILD_TOOL_PINS)
    return {name: pins[name] for name in _runtime_names(script)}


class TestGenerator:
    def test_the_lock_is_every_downloaded_wheel_with_its_hash(
        self, lock_script: ModuleType, tmp_path: Path
    ) -> None:
        versions = _all_versions(lock_script)
        commands, run = _fake_download(lock_script, versions)
        text = lock_script.generate(
            _freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=run, python="py"
        )
        entries = lock_script.parse_lock(text)
        assert set(entries) == set(versions)
        for name, (version, digest) in entries.items():
            assert version == versions[name]
            assert digest == hashlib.sha256(f"{name} {version}".encode()).hexdigest()
        assert list(entries) == sorted(entries)
        # One pip download, wheels only, constrained to the proven pins.
        [command] = commands
        assert command[:4] == ["py", "-m", "pip", "download"]
        assert "--only-binary=:all:" in command
        constraints = Path(command[command.index("--constraint") + 1]).read_text(encoding="utf-8")
        assert "pyinstaller-hooks-contrib==2026.8\n" in constraints
        assert "pytest==9.0.0\n" in constraints  # constraints only; never requested
        assert not any(c.startswith("pytest") for c in command[command.index("--constraint") + 2 :])

    def test_the_tool_pins_are_task_0_1s_recorded_versions(self, lock_script: ModuleType) -> None:
        assert dict(lock_script.BUILD_TOOL_PINS) == {
            "pyinstaller-hooks-contrib": "2026.8",
            "altgraph": "0.17.5",
            "pefile": "2024.8.26",
        }

    def test_an_unpinned_version_is_refused_by_name(
        self, lock_script: ModuleType, tmp_path: Path
    ) -> None:
        versions = _all_versions(lock_script) | {"numpy": "9.9.9"}
        _, run = _fake_download(lock_script, versions)
        with pytest.raises(lock_script.LockError, match="numpy 9.9.9 is not pinned"):
            lock_script.generate(_freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=run)

    def test_a_package_the_proven_environment_lacks_is_refused(
        self, lock_script: ModuleType, tmp_path: Path
    ) -> None:
        versions = _all_versions(lock_script) | {"surprise": "1.0"}
        _, run = _fake_download(lock_script, versions)
        with pytest.raises(lock_script.LockError, match="surprise 1.0 is not pinned"):
            lock_script.generate(_freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=run)

    def test_an_sdist_is_refused(self, lock_script: ModuleType, tmp_path: Path) -> None:
        _, run = _fake_download(lock_script, _all_versions(lock_script), ["thing-1.0.tar.gz"])
        with pytest.raises(lock_script.LockError, match="not a wheel"):
            lock_script.generate(_freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=run)

    @pytest.mark.parametrize("name", ["pyinstaller", "llama-cpp-python", "pytest"])
    def test_what_never_belongs_in_the_lock_is_refused(
        self, lock_script: ModuleType, tmp_path: Path, name: str
    ) -> None:
        freeze = _freeze(lock_script) + f"{name}==2.0\n"
        versions = _all_versions(lock_script) | {name: "2.0"}
        _, run = _fake_download(lock_script, versions)
        with pytest.raises(lock_script.LockError, match="must not be in the build lock"):
            lock_script.generate(freeze, PYPROJECT_TEXT, workdir=tmp_path, run=run)

    def test_a_missing_runtime_dependency_is_refused(
        self, lock_script: ModuleType, tmp_path: Path
    ) -> None:
        versions = _all_versions(lock_script)
        del versions["sounddevice"]
        _, run = _fake_download(lock_script, versions)
        with pytest.raises(lock_script.LockError, match="would miss: sounddevice"):
            lock_script.generate(_freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=run)

    def test_a_failed_download_writes_nothing(
        self, lock_script: ModuleType, tmp_path: Path
    ) -> None:
        with pytest.raises(lock_script.LockError, match="pip download failed"):
            lock_script.generate(
                _freeze(lock_script), PYPROJECT_TEXT, workdir=tmp_path, run=lambda c: 1
            )

    def test_the_freeze_skips_editable_and_url_lines(self, lock_script: ModuleType) -> None:
        pins = lock_script.proven_pins(_freeze(lock_script))
        assert "scribe-desktop" not in pins and "llama-cpp-python" not in pins
        assert lock_script.proven_pins("PyYAML==6.0.3\r\nPySide6_Addons==6.11.1\n") == {
            "pyyaml": "6.0.3",
            "pyside6-addons": "6.11.1",
        }

    @pytest.mark.parametrize(
        ("filename", "identity"),
        [
            ("numpy-2.5.1-cp314-cp314-win_amd64.whl", ("numpy", "2.5.1")),
            ("PySide6_Essentials-6.11.1-cp39-abi3-win_amd64.whl", ("pyside6-essentials", "6.11.1")),
            ("pywin32-312-1-cp314-cp314-win_amd64.whl", ("pywin32", "312")),
        ],
    )
    def test_wheel_names(
        self, lock_script: ModuleType, filename: str, identity: tuple[str, str]
    ) -> None:
        assert lock_script.wheel_identity(filename) == identity


class TestLockCoversTheRuntime:
    """The task's test: every pyproject runtime dependency appears in the
    lock — against a fixture lock always, and the committed lock once it
    exists."""

    def test_the_check_names_a_missing_dependency(self, lock_script: ModuleType) -> None:
        names = _runtime_names(lock_script)
        full = {name: ("1", "0" * 64) for name in names}
        assert lock_script.missing_runtime_dependencies(full, PYPROJECT_TEXT) == []
        partial = {k: v for k, v in full.items() if k not in {"pydantic", "faster-whisper"}}
        assert lock_script.missing_runtime_dependencies(partial, PYPROJECT_TEXT) == [
            "faster-whisper",
            "pydantic",
        ]

    def test_every_pyproject_dependency_is_checked(self, lock_script: ModuleType) -> None:
        project = tomllib.loads(PYPROJECT_TEXT)["project"]
        names = set(_runtime_names(lock_script))
        for requirement in [*project["dependencies"], *project["optional-dependencies"]["ml"]]:
            assert lock_script.requirement_name(requirement) in names

    def test_the_fixture_lock_round_trips(self, lock_script: ModuleType) -> None:
        entries = {"numpy": ("2.5.1", "a" * 64), "pydantic": ("2.13.4", "b" * 64)}
        text = lock_script.render_lock(entries, constraints_name="freeze.txt")
        assert lock_script.parse_lock(text) == entries

    @pytest.mark.skipif(not LOCK.is_file(), reason=_LOCK_ABSENT)
    def test_the_committed_lock_covers_the_runtime_and_is_fully_hashed(
        self, lock_script: ModuleType
    ) -> None:
        text = LOCK.read_text(encoding="utf-8")
        entries = lock_script.parse_lock(text)
        assert lock_script.missing_runtime_dependencies(entries, PYPROJECT_TEXT) == []
        requirement_lines = [
            line for line in text.splitlines() if line and not line.startswith(("#", " "))
        ]
        assert len(requirement_lines) == len(entries)  # every entry carries its hash
        assert not set(entries) & lock_script.NEVER_LOCKED
        for name, version in lock_script.BUILD_TOOL_PINS.items():
            assert entries[name][0] == version
